### ISSUE TITLE
Home loads too quick

### ISSUE THREAD

**Issue by tdscott10** [paulsoiya/teamj#19]
Sometimes home loads before the current user is set.  We need to decide how to slow it down.

**Comment by tdscott10** [comment]
I haven't run into this for a while.  If someone does let me know.

**Comment by zcmoore** [comment]
10 days ago I was able to reproduce this issue. Now I can't.

I'll review the code again to check for logic issues. if nothing shows up we should consider labeling this issue as "will not fix" and burying it.

**Comment by paulsoiya** [comment]
I also could not reproduce this issue right now. I wonder if we fixed this without knowing.

**Comment by zcmoore** [comment]
This might have been solved as a side effect of one of our refactors. I'd like to review it just in case, but I think it is safe to tag this as "will not fix", or "not reproducible"  or similar, and bury the issue.

Let me know your thoughts.

**Comment by tdscott10** [comment]
Closing this with the won't fix label.  If someone has it reappear we'll reopen it.
