### ISSUE TITLE
EditUser should pre-populate fields

### ISSUE THREAD

**Issue by zcmoore** [paulsoiya/teamj#20]
## Current Behaviour
* Navigating to EditUser "traps" the user in the edit screen and forces them to re-enter their information.
* Email is an editable field, but entering a value that is not the current email address results in an error message.

## Desired Behaviour
* The fields are auto-populated with the current user's information when the user navigated to the EditUser screen.
* Only fields which are allowed to be changed are editable
* User may navigate away from this page, without making changes, via the navigation bar

**Comment by tdscott10** [comment]
Should we remove the email address field?  Also we should not populate the password and leave it the same if null or blank.  We can do this after the code review tomorrow. I'll add a task for it.

**Comment by zcmoore** [comment]
1: Perhaps, instead of removing the email field, we should replace it with a label, as to clearly disallow edits (I'm afraid disabling the field may lead to the presumption that it can be changed under certain conditions). If we go with that, I'd suggest we also move the email field to the top of the list.

2: I agree. Maybe we go a step further and not show the password/confirm password fields at all unless the user clicks a "change password" link.

**Comment by zcmoore** [comment]
Commit: 76c7246
