### ISSUE TITLE
Share screen on quick compare allows you into the home page.

### ISSUE THREAD

**Issue by tdscott10** [paulsoiya/teamj#34]
We need a new fxml and controller to prevent this.

**Comment by zcmoore** [comment]
I seem to have forgotten why we made this a page instead of a popup. Was there some major benefit?

**Comment by tdscott10** [comment]
I'm all for a popup as long as it we don't need to rely on java 8u40 to get one.  I don't think anything is wrong with it functionally, but if we don't do a popup maybe take them back to the compare after the email has been sent.

**Comment by tdscott10** [comment]
Fixed in above commit. Sloppy but it will do.
