### ISSUE TITLE
Invalid Recent Games Screen Stalls

### ISSUE THREAD

**Issue by zcmoore** [paulsoiya/teamj#38]
Under certain conditions, adding a new row to the recent games screen can cause the program to hang.

The new row is added successfully, but the current client instance becomes unusable.

## Steps to Reproduce
1. Make a new account
2. Click recent games (without adding a sport)
3. Add a new row

**Comment by zcmoore** [comment]
Since the only sport we offer is Football, does it make since to keep the "add a sport" feature?

**Comment by zcmoore** [comment]
This issue has been resolved by the above commit, but still warrants discussion. I am keeping this open until the discussion concludes.

I think there are better ways to solve this problem (via redesign; see above)

**Comment by tdscott10** [comment]
I don't think it warrants a redesign.  We designed the application with having multiple sports in mind.  Since were only doing one sport to demonstrate our design, I think it is fine the way it is.
