### ISSUE TITLE
Cannot return to Compare Screen from Graph view

### ISSUE THREAD

**Issue by zcmoore** [paulsoiya/teamj#40]
## Current Behaviour
Clicking "Graph" from the compare screen removes the image, and breaks any link back to the compare view.

## Desired Behaviour
On the graph view, the "Graph" button is replaced by a "Stats" button, or similar, which returns the user to the stats/compare view.

The image should either be kept, or the view should be rearranged.

**Comment by tdscott10** [comment]
Let's hold off on these and let Jamie finish them.

**Comment by zcmoore** [comment]
Agreed. Just thought I'd report/mention it in the meantime.

**Comment by tdscott10** [comment]
Closed because Jamie's finished graph fixes this.
