### ISSUE TITLE
Auto-Select on Graph View

### ISSUE THREAD

**Issue by zcmoore** [paulsoiya/teamj#42]
## Current Behaviour
After clicking "Graph" on the Compare Screen, the "Share" button is automatically selected and highlighted.

## Desired Behaviour
Share should not be highlighted after selecting the graph button.

**Comment by tdscott10** [comment]
Let's hold off on these and let Jamie finish them.

**Comment by tdscott10** [comment]
Closed because Jamie's finished graph fixes this.
